In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [5]:
df=pd.read_csv('/Users/shahranhossain/Personal Drive/AI resume shorlister (SH)/resume_data.csv')

In [6]:
df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [7]:
df.shape

(9544, 35)

In [8]:
df.isnull().sum()

address                                8760
career_objective                       4804
skills                                   56
educational_institution_name             84
degree_names                             84
passing_years                            84
educational_results                      84
result_types                             84
major_field_of_studies                   84
professional_company_names               84
company_urls                             84
start_dates                              84
end_dates                                84
related_skils_in_job                     84
positions                                84
locations                                84
responsibilities                          0
extra_curricular_activity_types        6118
extra_curricular_organization_names    6118
extra_curricular_organization_links    6118
role_positions                         6118
languages                              8844
proficiency_levels                     8844
certification_providers                7536
certification_skills                   7536
online_links                           7536
issue_dates                            7536
expiry_dates                           7536
﻿job_position_name                        0
educationaL_requirements                  0
experiencere_requirement               1364
age_requirement                        4087
responsibilities.1                        0
skills_required                        1701
matched_score                             0
dtype: int64

In [9]:
df.isnull().sum()/df.shape[0]*100

address                                91.785415
career_objective                       50.335289
skills                                  0.586756
educational_institution_name            0.880134
degree_names                            0.880134
passing_years                           0.880134
educational_results                     0.880134
result_types                            0.880134
major_field_of_studies                  0.880134
professional_company_names              0.880134
company_urls                            0.880134
start_dates                             0.880134
end_dates                               0.880134
related_skils_in_job                    0.880134
positions                               0.880134
locations                               0.880134
responsibilities                        0.000000
extra_curricular_activity_types        64.103101
extra_curricular_organization_names    64.103101
extra_curricular_organization_links    64.103101
role_positions                         64.103101
languages                              92.665549
proficiency_levels                     92.665549
certification_providers                78.960604
certification_skills                   78.960604
online_links                           78.960604
issue_dates                            78.960604
expiry_dates                           78.960604
﻿job_position_name                      0.000000
educationaL_requirements                0.000000
experiencere_requirement               14.291702
age_requirement                        42.822716
responsibilities.1                      0.000000
skills_required                        17.822716
matched_score                           0.000000
dtype: float64

In [10]:
##dropped columns that have null value greater than 60%

null_percentages = df.isnull().sum() / df.shape[0] * 100
columns_to_drop = null_percentages[null_percentages > 60].index
df_dropped = df.drop(columns=columns_to_drop)
display(df_dropped.head())

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,company_urls,...,positions,locations,responsibilities,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],[None],...,['Big Data Analyst'],['N/A'],Technical Support\nTroubleshooting\nCollaborat...,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],['N/A'],...,['Business Analyst'],['N/A'],Machine Learning Leadership\nCross-Functional ...,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],['N/A'],...,['Software Developer (Machine Learning Enginee...,['N/A'],"Trade Marketing Executive\nBrand Visibility, S...","Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","[None, None, None, None, None, None]",...,"['Accountant', 'Accounts Receivable Clerk', 'M...","['City, State', 'City, State', 'City, State', ...",Apparel Sourcing\nQuality Garment Sourcing\nRe...,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","[None, None, None, None, None]",...,"['Staff Accountant', 'Senior Accountant', 'Tax...","['City, State', 'City, State', 'City, State', ...",iOS Lifecycle\nRequirement Analysis\nNative Fr...,Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [11]:
for column in df_dropped.columns:
    if df_dropped[column].dtype == 'object':
        df_dropped[column].fillna('Unknown', inplace=True)

# You can also use other methods like forward fill (ffill), backward fill (bfill), or fill with mean/median/mode for numerical columns.
# For example:
# df_dropped['numerical_column'].fillna(df_dropped['numerical_column'].mean(), inplace=True)

display(df_dropped.isnull().sum())

/var/folders/12/qq3mfp456z77ztrpn5c2nhz80000gn/T/ipykernel_25657/2557333214.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_dropped[column].fillna('Unknown', inplace=True)

career_objective                0
skills                          0
educational_institution_name    0
degree_names                    0
passing_years                   0
educational_results             0
result_types                    0
major_field_of_studies          0
professional_company_names      0
company_urls                    0
start_dates                     0
end_dates                       0
related_skils_in_job            0
positions                       0
locations                       0
responsibilities                0
﻿job_position_name              0
educationaL_requirements        0
experiencere_requirement        0
age_requirement                 0
responsibilities.1              0
skills_required                 0
matched_score                   0
dtype: int64

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Combine the text from the specified columns into a single column
df_dropped['combined_text'] = df_dropped['career_objective'].fillna('') + ' ' + \
                             df_dropped['skills'].fillna('') + ' ' + \
                             df_dropped['responsibilities'].fillna('')

# Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=5000) # You can adjust max_features

# Fit and transform the combined text
tfidf_matrix = tfidf_vectorizer.fit_transform(df_dropped['combined_text'])

# You can now use tfidf_matrix for further analysis (e.g., clustering, similarity calculations)
print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (9544, 3062)

In [13]:
df_dropped.to_csv('cleaned_resume_data.csv', index=False)
print("Cleaned dataset saved to 'cleaned_resume_data.csv'")

Cleaned dataset saved to 'cleaned_resume_data.csv'

In [14]:
cleaned_df = pd.read_csv('cleaned_resume_data.csv')
display(cleaned_df.head())
display(cleaned_df.info())
display(cleaned_df.isnull().sum())

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,company_urls,...,locations,responsibilities,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score,combined_text
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],[None],...,['N/A'],Technical Support\nTroubleshooting\nCollaborat...,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,Unknown,Technical Support\nTroubleshooting\nCollaborat...,Unknown,0.850000,Big data analytics working and database wareho...
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],['N/A'],...,['N/A'],Machine Learning Leadership\nCross-Functional ...,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),Unknown,Machine Learning Leadership\nCross-Functional ...,Unknown,0.750000,Fresher looking to join as a data analyst and ...
2,Unknown,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],['N/A'],...,['N/A'],"Trade Marketing Executive\nBrand Visibility, S...","Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,Unknown,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667,"Unknown ['Software Development', 'Machine Lear..."
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","[None, None, None, None, None, None]",...,"['City, State', 'City, State', 'City, State', ...",Apparel Sourcing\nQuality Garment Sourcing\nRe...,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000,To obtain a position in a fast-paced business ...
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","[None, None, None, None, None]",...,"['City, State', 'City, State', 'City, State', ...",iOS Lifecycle\nRequirement Analysis\nNative Fr...,Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,Unknown,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000,Professional accountant with an outstanding wo...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   career_objective              9544 non-null   object
 1   skills                        9544 non-null   object
 2   educational_institution_name  9544 non-null   object
 3   degree_names                  9544 non-null   object
 4   passing_years                 9544 non-null   object
 5   educational_results           9544 non-null   object
 6   result_types                  9544 non-null   object
 7   major_field_of_studies        9544 non-null   object
 8   professional_company_names    9544 non-null   object
 9   company_urls                  9544 non-null   object
 10  start_dates                   9544 non-null   object
 11  end_dates                     9544 non-null   object
 12  related_skils_in_job          9544 non-null   object
 13  positions                     9544 non-null   object
 14  locations                     9544 non-null   object
 15  responsibilities              9544 non-null   object
 16  ﻿job_position_name            9544 non-null   object
 17  educationaL_requirements      9544 non-null   object
 18  experiencere_requirement      9544 non-null   object
 19  age_requirement               9544 non-null   object
 20  responsibilities.1            9544 non-null   object
 21  skills_required               9544 non-null   object
 22  matched_score                 9544 non-null   float64
 23  combined_text                 9544 non-null   object
dtypes: float64(1), object(23)
memory usage: 1.7+ MB

None

career_objective                0
skills                          0
educational_institution_name    0
degree_names                    0
passing_years                   0
educational_results             0
result_types                    0
major_field_of_studies          0
professional_company_names      0
company_urls                    0
start_dates                     0
end_dates                       0
related_skils_in_job            0
positions                       0
locations                       0
responsibilities                0
﻿job_position_name              0
educationaL_requirements        0
experiencere_requirement        0
age_requirement                 0
responsibilities.1              0
skills_required                 0
matched_score                   0
combined_text                   0
dtype: int64

In [15]:
# Display the head of the dataframe
display(cleaned_df.head())

# Display descriptive statistics for numerical columns
display(cleaned_df.describe())

# Display descriptive statistics for object columns (including counts of unique values)
display(cleaned_df.describe(include='object'))

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,company_urls,...,locations,responsibilities,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score,combined_text
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],[None],...,['N/A'],Technical Support\nTroubleshooting\nCollaborat...,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,Unknown,Technical Support\nTroubleshooting\nCollaborat...,Unknown,0.850000,Big data analytics working and database wareho...
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],['N/A'],...,['N/A'],Machine Learning Leadership\nCross-Functional ...,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),Unknown,Machine Learning Leadership\nCross-Functional ...,Unknown,0.750000,Fresher looking to join as a data analyst and ...
2,Unknown,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],['N/A'],...,['N/A'],"Trade Marketing Executive\nBrand Visibility, S...","Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,Unknown,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667,"Unknown ['Software Development', 'Machine Lear..."
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","[None, None, None, None, None, None]",...,"['City, State', 'City, State', 'City, State', ...",Apparel Sourcing\nQuality Garment Sourcing\nRe...,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000,To obtain a position in a fast-paced business ...
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","[None, None, None, None, None]",...,"['City, State', 'City, State', 'City, State', ...",iOS Lifecycle\nRequirement Analysis\nNative Fr...,Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,Unknown,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000,Professional accountant with an outstanding wo...

       matched_score
count    9544.000000
mean        0.660831
std         0.167040
min         0.000000
25%         0.583333
50%         0.683333
75%         0.793333
max         0.970000

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,company_urls,...,positions,locations,responsibilities,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,combined_text
count,9544,9544,9544,9544,9544,9544,9544,9544,9544,9544,...,9544,9544,9544,9544,9544,9544,9544,9544,9544,9544
unique,172,341,329,181,150,79,31,211,200,17,...,302,87,28,28,20,18,15,28,24,9544
top,Unknown,Unknown,"['Illinois Institute of Technology', 'National...",['B.Tech'],['2019'],['N/A'],['N/A'],['N/A'],"['Company Name', 'Company Name', 'Company Name']",['N/A'],...,['Intern'],['N/A'],Supervision\nMonitoring\nConstruction\nEstimat...,Site Engineer,Bachelor/Honors,Unknown,Unknown,Supervision\nMonitoring\nConstruction\nEstimat...,Unknown,Big data analytics working and database wareho...
freq,4804,56,112,1764,1428,3612,3416,616,1204,2436,...,392,3164,342,342,2044,1364,4087,342,1701,1

In [16]:
# Analyze value counts for some categorical columns
display(cleaned_df['﻿job_position_name'].value_counts().head(10))
display(cleaned_df['educationaL_requirements'].value_counts().head(10))
display(cleaned_df['experiencere_requirement'].value_counts().head(10))

job_position_name
Site Engineer                                             342
Project Coordinator (Civil)                               342
Civil Engineer                                            342
HR Officer                                                342
Marketing Officer                                         341
Manager- Human Resource Management (HRM)\n                341
Head of Internal Control & Compliance (ICC) - SEVP/DMD    341
Management Trainee - Mechanical                           341
Sr.Officer / Executive - Internal Audit                   341
Executive - VAT                                           341
Name: count, dtype: int64

educationaL_requirements
Bachelor/Honors                                                                                                                     2044
Bachelor of Science (BSc) in Computer Science                                                                                        681
Bachelor of Science (BSc) in Computer Science & Engineering                                                                          680
Bachelor of Science (BSc)                                                                                                            680
Bachelor of Science (BSc) in Civil Engineering                                                                                       342
B.Sc in Civil Engineering from a reputed university.                                                                                 342
•Bachelor of Business Administration (BBA) in Human Resource Management\n•BBA/MBA in HRM/Management from any reputed university.     342
•Bachelor of Business Administration (BBA) in Human Resource Management                                                              342
Master of Commerce (MCom) in Accounting, Must have CACC certification from any CA firm                                               341
Masters degree in any discipline, Bachelor of Business Administration (BBA)                                                          341
Name: count, dtype: int64

experiencere_requirement
Unknown             1364
At least 5 years    1024
At least 1 year     1023
At least 3 years    1022
1 to 3 years         682
5 to 10 years        342
1 to 2 years         342
2 to 5 years         341
4 to 5 years         341
2 to 4 years         341
Name: count, dtype: int64

In [17]:
y = cleaned_df['matched_score']
X = cleaned_df.drop('matched_score', axis=1)
display(X.head())
display(y.head())

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,company_urls,...,positions,locations,responsibilities,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,combined_text
0,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],[None],...,['Big Data Analyst'],['N/A'],Technical Support\nTroubleshooting\nCollaborat...,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,Unknown,Technical Support\nTroubleshooting\nCollaborat...,Unknown,Big data analytics working and database wareho...
1,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],['N/A'],...,['Business Analyst'],['N/A'],Machine Learning Leadership\nCross-Functional ...,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),Unknown,Machine Learning Leadership\nCross-Functional ...,Unknown,Fresher looking to join as a data analyst and ...
2,Unknown,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],['N/A'],...,['Software Developer (Machine Learning Enginee...,['N/A'],"Trade Marketing Executive\nBrand Visibility, S...","Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,Unknown,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,"Unknown ['Software Development', 'Machine Lear..."
3,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...","[None, None, None, None, None, None]",...,"['Accountant', 'Accounts Receivable Clerk', 'M...","['City, State', 'City, State', 'City, State', ...",Apparel Sourcing\nQuality Garment Sourcing\nRe...,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,To obtain a position in a fast-paced business ...
4,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...","[None, None, None, None, None]",...,"['Staff Accountant', 'Senior Accountant', 'Tax...","['City, State', 'City, State', 'City, State', ...",iOS Lifecycle\nRequirement Analysis\nNative Fr...,Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,Unknown,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,Professional accountant with an outstanding wo...

0    0.850000
1    0.750000
2    0.416667
3    0.760000
4    0.650000
Name: matched_score, dtype: float64

In [19]:
# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include='object').columns.tolist()
# Exclude 'combined_text' from categorical encoding as we'll use its TF-IDF representation
categorical_cols.remove('combined_text')

# Apply one-hot encoding to categorical features
X_categorical = pd.get_dummies(X[categorical_cols], dummy_na=False)

# Ensure indices align before concatenating
X_categorical.index = cleaned_df.index

# Concatenate one-hot encoded features with TF-IDF matrix
X_processed = pd.concat([X_categorical, pd.DataFrame(tfidf_matrix.toarray(), index=cleaned_df.index)], axis=1)

display(X_processed.head())

,"career_objective_A Data Science enthusiast with a demonstrated history of working in Banking industry. Currently working on real life Data Science projects with interest in Predictive Analytics, Machine Learning and Deep Learning.","career_objective_A Fresher Seeking Roles In Machine Learning, Business Analysis, Data Predictive Modelling, Statistical Solutions, Data Mining.","career_objective_A Software Designer Internship with a client-driven corporation leading the field of wireless communication, where outstanding success in team projects, involving design and implementation of software, as well as proven ability to deliver high quality projects on-time will contribute to the implementation, testing and support of innovative wireless products.","career_objective_A business management graduate with significant experience in disability services, human resources and finance department; seeking to apply my abilities to position in a human resource department. Proven ability to deal with multiple tasks efficiently and maintain organization.","career_objective_A challenging position in a Manufacturing, Engineering, or Research & Development environment where my overall technical background, along with my leadership and decision making capabilities will be combined to contribute to company goals, enlargement, & productivity.","career_objective_A curiosity-driven data scientist, eager to leverage machine learning and data analytics to extract meaningful insights, make informed decisions and solve challenging business problems. I ensure to contribute with my knowledge, logical thinking and analytical skills towards the consistent growth and development of the organization, and enhance my experience through continuous learning and teamwork.",career_objective_A highly disciplined and hard-working individual seeking challenging opportunity in the field of data science and data analytics where I can utilize my skills and knowledge to contribute for the growth of the organization,"career_objective_A highly experienced skilled graduate with Analytics degree with a very good experience in SAS, Web scraping, SQL, Predictive modelling and data visualization. Excellent ability in identifying data requirements for analysis, data cleaning, munging and model building; Ensures the organization uses it effectively to reach profit and growth objectives. Comfortable with data handling, modeling, and coding, and have an appreciation of what makes sense from a business standpoint. More than six years of experience working as a researcher, data analyst, and environmental science and Technology Instructor. Experience in SQL, data warehousing, maintaining, securing and stabilizing data layers and testing to identify data and product defects introduced in the system. Customer segmentation, product positioning and mapping and conjoint analysis Modelling: Design and implement statistical / predictive models and cutting edge algorithms utilizing diverse sources of data to predict Diversified experience with Engineering, Manufacturing, Retailing, Higher Education and IT /Data related companies Fascinated by learning cutting edge technologies, such as; Data Mining and Machine Learning Handled a team of 4 during my 3 years of Tech experience and managed more than 200 students and effectively evaluated the performance of each student and utilize assessment methods to judge overall progress during my teaching experience.","career_objective_A practiced, professional Test Manager with over 20 years of success managing test and validation of next-generation software / hardware technologies across multiple concurrent projects and releases. Delivered effectively to time and budget on a variety of complex, large-scale, multiplatform projects including: complex network framework, IoT (Internet of Things), telecommunication and hosted services, business process tools, automation frameworks. Managed, trained and mentored multi-disciplinary, geographically dispersed teams including, software development, test and validation, planning, QA, configuration management, agile scrum master and product owner.","career_objective_A python programmer, currently pursuing Data science and looking for roles that involve the application of Machine Learning. I am always excited to take on real life problems and tread through different technology stacks.",...,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061
0,False,False,False,False,False,False,False,False,False,False,...,0.0,0.187437,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,False,False,False,False,False,False,False,False,False,False,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,False,False,False,False,False,False,False,False,False,False,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,False,False,False,False,False,False,False,False,False,False,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,False,False,False,False,False,False,False,False,False,False,...,0.0,0.000000,0.094267,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (7635, 6122)
Shape of X_test: (1909, 6122)
Shape of y_train: (7635,)
Shape of y_test: (1909,)

In [25]:
from xgboost import XGBRegressor

ModuleNotFoundError: No module named 'xgboost'

In [26]:
# First, install the xgboost package
!pip install xgboost

# Then import it
from xgboost import XGBRegressor

# Note: You may need to restart your kernel after installing the package
# for the changes to take effect

Collecting xgboost
  Using cached xgboost-3.1.1-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)
Using cached xgboost-3.1.1-py3-none-macosx_12_0_arm64.whl (2.2 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.1.1

In [27]:
# Convert all column names to strings and then clean
X_train.columns = [str(col).replace('[', '').replace(']', '').replace('<', '') for col in X_train.columns]
X_test.columns = [str(col).replace('[', '').replace(']', '').replace('<', '') for col in X_test.columns]

# Initialize the XGBoost Regressor model
xgb_model = XGBRegressor(random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [28]:
y_train_pred = xgb_model.predict(X_train)
y_test_pred = xgb_model.predict(X_test)

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Calculate evaluation metrics for training set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
mae_train = mean_absolute_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)

# Calculate evaluation metrics for testing set
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = np.sqrt(mse_test)
mae_test = mean_absolute_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print("Training Set Metrics:")
print(f"  MSE: {mse_train:.4f}")
print(f"  RMSE: {rmse_train:.4f}")
print(f"  MAE: {mae_train:.4f}")
print(f"  R-squared: {r2_train:.4f}")

print("\nTesting Set Metrics:")
print(f"  MSE: {mse_test:.4f}")
print(f"  RMSE: {rmse_test:.4f}")
print(f"  MAE: {mae_test:.4f}")
print(f"  R-squared: {r2_test:.4f}")

Training Set Metrics:
  MSE: 0.0037
  RMSE: 0.0607
  MAE: 0.0465
  R-squared: 0.8682

Testing Set Metrics:
  MSE: 0.0108
  RMSE: 0.1040
  MAE: 0.0767
  R-squared: 0.6089